<?php
declare(strict_types=1);
session_start(); require dirname(__DIR__).'/db.php'; require dirname(__DIR__).'/complaints.php';
initialiseDatabase(); requirePanelAccess();
if (!hasFullAccess()) { http_response_code(403); exit('Acesso restrito à administração.'); }
initialiseComplaints();
header('Cache-Control: no-store'); header('Referrer-Policy: no-referrer'); header('X-Content-Type-Options: nosniff'); header('X-Robots-Tag: noindex, nofollow');
function ch(mixed $v): string { return htmlspecialchars((string)$v,ENT_QUOTES|ENT_SUBSTITUTE,'UTF-8'); }
$csrf=$_SESSION['complaint_admin_csrf']??=bin2hex(random_bytes(32)); $error=''; $id=is_string($_GET['case']??null)?$_GET['case']:''; $case=null;
if ($id) { try { $case=complaintGet($id); } catch (Throwable $e) { http_response_code(404); exit('Registro indisponível.'); } }
if ($case && isset($_GET['file'])) {
    if ($case['status']==='unconfirmed') { http_response_code(403); exit('Aguarde a confirmação do registro.'); }
    complaintDownload($id,is_string($_GET['file'])?$_GET['file']:'','admin');
}
if ($_SERVER['REQUEST_METHOD']==='POST') {
    try {
        if (!is_string($_POST['csrf']??null) || !hash_equals($csrf,$_POST['csrf'])) { http_response_code(400); throw new RuntimeException('Solicitação inválida. Recarregue a página.'); }
        complaintAdminAction($id,$_POST); header('Location: denuncias.php?case='.$id.'&saved=1'); exit;
    } catch (PDOException $e) { $error='Não foi possível concluir agora. Tente novamente em instantes.'; }
    catch (RuntimeException $e) { $error=$e->getMessage(); } catch (Throwable $e) { $error='Não foi possível concluir a ação. Recarregue e tente novamente.'; }
    $case=complaintGet($id);
}
function hiddenCase(array $case, string $csrf, string $action): string { return '<input type="hidden" name="csrf" value="'.ch($csrf).'"><input type="hidden" name="revision" value="'.ch($case['revision']).'"><input type="hidden" name="action" value="'.ch($action).'">'; }
?><!doctype html><html lang="pt-BR"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Denúncias · Administração</title><link rel="stylesheet" href="admin.css"><link rel="stylesheet" href="complaints.css?v=<?= copaVersion() ?>"></head><body><main class="complaint-shell"><a href="admin.php">← Painel</a><h1>Canal de denúncias</h1><p>Informações reservadas para apuração. Não presuma culpa. Se você estiver envolvido, peça a outro administrador que conduza o caso. Os prazos e a decisão devem seguir as regras acordadas pela organização.</p><?php if ($error): ?><p class="error" role="alert"><?= ch($error) ?></p><?php endif ?><?php if (isset($_GET['saved'])): ?><p class="flash" role="status">Ação registrada. Confira abaixo a situação dos avisos por e-mail.</p><?php endif ?>
<?php if (!$case): ?>
<p>Registros sem confirmação ainda não foram encaminhados para análise. São exibidos apenas para suporte ao envio do e-mail.</p>
<?php $page=max(1,(int)($_GET['page']??1)); $total=(int)complaintQuery('SELECT COUNT(*) FROM complaints')->fetchColumn(); $page=min($page,max(1,(int)ceil($total/25))); $rows=complaintQuery('SELECT id,protocol,status,created_at FROM complaints ORDER BY created_at DESC,rowid DESC LIMIT 25 OFFSET '.(($page-1)*25))->fetchAll(); ?>
<?php if (!$rows): ?><p>Nenhum registro recebido.</p><?php endif ?><?php foreach ($rows as $row): ?><article class="complaint-event"><a href="?case=<?= ch($row['id']) ?>"><strong><?= ch($row['protocol']) ?></strong></a><p><?= ch(complaintStatus($row['status'])) ?> · <?= ch(date('d/m/Y H:i',$row['created_at'])) ?></p></article><?php endforeach ?>
<nav aria-label="Páginas de registros"><?php if ($page>1): ?><a href="?page=<?= $page-1 ?>">Anterior</a><?php endif ?> <span>Página <?= $page ?></span> <?php if ($page*25<$total): ?><a href="?page=<?= $page+1 ?>">Próxima</a><?php endif ?></nav>
<?php else: ?>
<a href="denuncias.php">Todos os registros</a><h2><?= ch($case['protocol']) ?></h2><p><strong><?= ch(complaintStatus($case['status'])) ?></strong></p>
<?php if ($case['status']!=='unconfirmed'): ?>
<p>Denunciante: <?= ch($case['name']) ?><br>E-mail confirmado: <?= ch($case['email']) ?><br>Telefone para contato (não verificado): <?= ch($case['phone']) ?></p><h3>Envolvidos</h3><p><?= ch($case['subject']) ?></p><h3>Relato original</h3><div class="complaint-text"><?= ch($case['description']) ?></div>
<?php if ($case['shared_summary']): ?><h3>Texto encaminhado à defesa</h3><div class="complaint-text"><?= ch($case['shared_summary']) ?></div><p>Convite para <?= ch($case['defense_email']) ?>. Prazo: <?= ch(date('d/m/Y H:i',$case['defense_until'])) ?></p><?php endif ?>
<h3>Histórico reservado</h3><?php foreach (complaintQuery('SELECT * FROM complaint_events WHERE complaint_id=? ORDER BY occurred_at,rowid',[$id])->fetchAll() as $event): ?><article class="complaint-event"><small><?= ch(date('d/m/Y H:i',$event['occurred_at'])) ?> · <?= ch($event['actor']) ?> · Visível para: <?= ch(['author'=>'denunciante','defense'=>'defesa','both'=>'ambas as partes'][$event['audience']]) ?></small><div class="complaint-text"><?= ch($event['message']) ?></div></article><?php endforeach ?>
<h3>Anexos</h3><?php foreach (complaintQuery('SELECT id,name,audience FROM complaint_files WHERE complaint_id=?',[$id])->fetchAll() as $file): ?><p><a href="?case=<?= ch($id) ?>&amp;file=<?= ch($file['id']) ?>"><?= ch($file['name']) ?></a> · <?= $file['audience']==='both'?'Compartilhado com ambas as partes':'Reservado ao remetente e à administração' ?></p><?php if ($file['audience']!=='both' && !in_array($case['status'],['closed','archived'],true)): ?><form method="post"><?= hiddenCase($case,$csrf,'share') ?><input type="hidden" name="file" value="<?= ch($file['id']) ?>"><button class="button button-outline-dark">Compartilhar este anexo com ambas as partes</button></form><?php endif ?><?php endforeach ?>
<?php if (!in_array($case['status'],['closed','archived'],true)): ?>
<details><summary>Solicitar defesa / definir novo prazo</summary><p>Confira o e-mail da pessoa citada. Escreva os fatos e esclarecimentos necessários à defesa. Não copie contatos do denunciante. Se necessário, compartilhe os anexos relevantes acima. Um novo convite invalida o link de defesa anterior.</p><form method="post"><?= hiddenCase($case,$csrf,'invite') ?><label>E-mail da pessoa citada<input name="email_defesa" type="email" required value="<?= ch($case['defense_email']) ?>"></label><label>Prazo para responder<input name="prazo" type="date" min="<?= date('Y-m-d') ?>" required></label><label>Resumo enviado à defesa<textarea name="resumo_defesa" minlength="30" maxlength="10000" rows="6" required><?= ch($case['shared_summary']) ?></textarea></label><button class="button button-primary">Enviar convite para defesa</button></form></details>
<details><summary>Enviar mensagem ou pedir esclarecimentos</summary><form method="post"><?= hiddenCase($case,$csrf,'message') ?><label>Destinatário<select name="audience"><option value="author">Denunciante</option><option value="defense">Pessoa convidada para defesa</option><option value="both">Ambas as partes</option></select></label><label>Mensagem<textarea name="mensagem" rows="5" minlength="10" maxlength="10000" required></textarea></label><button class="button button-primary">Registrar e enviar mensagem</button></form></details>
<details><summary>Registrar conclusão</summary><p>Para concluir a apuração, é necessário receber a defesa ou aguardar o prazo concedido. Arquivar sem punição também exige justificativa. Nenhuma ação nesta tela altera placares ou aplica sanções automaticamente.</p><form method="post"><input type="hidden" name="csrf" value="<?= ch($csrf) ?>"><input type="hidden" name="revision" value="<?= ch($case['revision']) ?>"><label>Encaminhamento<select name="action"><option value="close">Concluir apuração</option><option value="archive">Arquivar sem punição</option></select></label><label>Justificativa comunicada às partes<textarea name="justificativa" rows="6" minlength="20" maxlength="10000" required></textarea></label><button class="button button-primary">Registrar conclusão</button></form></details>
<?php endif ?><?php else: ?><p>A confirmação ainda não ocorreu. O relato não está liberado para análise. Se o link expirou após 48 horas, oriente a pessoa a preencher um novo registro.</p><?php endif ?>
<h3>Avisos por e-mail</h3><p>Aceito pelo servidor não confirma a chegada à caixa de entrada. O registro permanece salvo se o envio falhar.</p><?php foreach (complaintQuery('SELECT recipient,status,attempts FROM complaint_mail WHERE complaint_id=? ORDER BY rowid',[$id])->fetchAll() as $mail): ?><p><?= ch($mail['recipient']) ?> — <?= ch(['pending'=>'Aguardando envio','sending'=>'Em envio','sent'=>'Aceito pelo servidor','failed'=>'Falha no envio'][$mail['status']]) ?> (<?= ch($mail['attempts']) ?> tentativa(s))</p><?php endforeach ?>
<?php if ($case['status']!=='unconfirmed'): ?><form method="post"><?= hiddenCase($case,$csrf,'renew') ?><button class="button button-outline-dark">Enviar novo link de acompanhamento ao denunciante</button></form><?php endif ?>
<form method="post"><?= hiddenCase($case,$csrf,'retry') ?><button class="button button-outline-dark">Reenviar avisos que falharam</button></form>
<?php endif ?><?= copaHelpFooter() ?></main></body></html>
