<?php
declare(strict_types=1);
require_once dirname(__DIR__) . '/version.php';
?>
<!doctype html>
<html lang="pt-BR"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Guia de uso · Copa Lago de Pedra</title><link rel="stylesheet" href="guia.css?v=<?= filemtime(__DIR__.'/guia.css') ?>"></head><body>
<a class="skip" href="#conteudo">Pular para o guia</a>
<header><div class="wrap"><p class="eyebrow">I COPA LAGO DE PEDRA · <?= copaVersionButton() ?></p><h1>A copa, sem complicação.</h1><p>Um guia para consultar os jogos, preencher a súmula e usar o painel com tranquilidade.</p><nav aria-label="Acesso rápido"><a href="index.php">← Voltar à área pública</a><a href="admin.php">Acessar o painel</a><button type="button" onclick="document.querySelectorAll('details').forEach(item => item.open = true); window.print()">Imprimir / salvar em PDF</button></nav></div></header>
<main id="conteudo" class="wrap"><aside class="intro"><strong>Comece por aqui</strong><p>Para ver a classificação e os jogos, você não precisa de senha. Para alterar informações, entre no painel com a sua conta.</p></aside>
<nav class="contents" aria-label="Assuntos do guia"><a href="#consulta">1. Consultar a copa</a><a href="#acesso">2. Entrar e sair</a><a href="#resultados">3. Salvar resultados</a><a href="#sumula">4. Súmula e QR Code</a><a href="#nomes">5. Corrigir meu nome</a><a href="#perfis">6. Permissões</a><a href="#auditoria">7. Auditoria e backups</a><a href="#duvidas">8. Dúvidas frequentes</a></nav>
<section id="consulta"><p class="step">01 · PARA TODOS</p><h2>Consulte a classificação e os jogos</h2><p>O campeonato tem turno e returno: no turno, os participantes se enfrentam pela primeira vez; no returno, voltam a enfrentar os mesmos adversários. Use as três abas da página pública. A aba selecionada fica com fundo verde escuro.</p>
<figure><div class="demo-tabs"><span class="selected">Classificação</span><span>Jogos</span><span>Evolução</span></div><figcaption>Ilustração das abas. No site, toque na aba que deseja abrir.</figcaption></figure>
<ul><li><strong>Classificação:</strong> veja a posição e os números dos botonistas. Use a busca para encontrar um nome. Os favoritos ficam salvos neste dispositivo e continuam marcados quando o nome do botonista é corrigido. Favoritos antigos são convertidos quando o nome ainda corresponde ao cadastro; se ele já mudou, marque a estrela novamente.</li><li><strong>Jogos:</strong> filtre por botonista, rodada e situação. “Com resultado” tem placar salvo; “Sem resultado” ainda aguarda informação.</li><li><strong>Evolução:</strong> escolha um botonista para ver sua posição e seus pontos ao final de cada data com jogos. A primeira data aparece como um ponto; a partir da segunda, o gráfico mostra a mudança. Correções de placar ou data recalculam o histórico. Jogos sem data válida contam na classificação atual, mas ficam fora da evolução, com aviso de histórico parcial.</li></ul>
<p>“50 de 650 jogos”, por exemplo, significa que 50 partidas correspondem aos filtros, de um total de 650 no campeonato. Não significa que todas já aconteceram ou aparecem na mesma página.</p>
<div class="tip"><strong>Quer letras maiores?</strong> Use <b>A+</b> na página pública. Para diminuir, use <b>A−</b>. Você também pode ampliar a página pelo navegador.</div>
<h3>Como são calculados os pontos?</h3><p>Vitória vale <strong>3 pontos</strong>, empate vale <strong>1 ponto</strong> e derrota vale <strong>0</strong>. A ordem da classificação considera pontos ganhos (PG), número de vitórias (V), saldo de gols (SG) e gols marcados (GM). O saldo é a diferença entre gols marcados e sofridos. Empates em todos esses critérios compartilham a posição.</p></section>
<section id="acesso"><p class="step">02 · SUA CONTA</p><h2>Entre no painel e volte ao site</h2><ol><li>No rodapé da página pública, toque em <strong>Acesso ao painel</strong>.</li><li>Informe seu login ou e-mail e a senha cadastrada.</li><li>Toque em <strong>Entrar no painel</strong>.</li></ol>
<figure><div class="login-demo"><strong>Atualizar resultados</strong><span>Login ou e-mail</span><div class="field">seu.login</div><span>Senha</span><div class="field">••••••••</div><div class="demo-button">Entrar no painel</div><div class="demo-outline">← Voltar à área pública</div></div><figcaption>Exemplo ilustrativo da tela de entrada; não é um formulário de login.</figcaption></figure>
<p>O botão <strong>Voltar à área pública</strong> permite sair da tela de entrada sem fazer login. Dentro do painel, use <strong>Ver site público</strong> ou o link <strong>Área pública</strong>. Para encerrar a sessão, use <strong>Sair</strong>; voltar ao site não desconecta sua conta.</p>
<div class="tip"><strong>Errou a senha várias vezes?</strong> Após 5 tentativas incorretas em 15 minutos, aquele acesso fica bloqueado por 15 minutos. Aguarde o prazo indicado na tela. Tentar novamente durante o bloqueio não aumenta o prazo. O controle vale para o painel e a súmula, combinando sua conta e a conexão usada. Outros usuários na mesma rede continuam podendo entrar, e a consulta pública permanece livre.</div>
<p>Se recebeu um convite por e-mail, abra o link para definir a senha. O convite vence em 72 horas e pode ser usado uma vez. Se estiver vencido, peça um novo ao responsável.</p></section>
<section id="resultados"><p class="step">03 · JOGOS AUTORIZADOS</p><h2>Registre ou corrija um resultado</h2><ol><li>No painel, encontre a partida pelos jogadores e pela rodada.</li><li>Preencha os gols dos dois jogadores e a data em que o jogo aconteceu. Datas inexistentes, como 31 de fevereiro, são recusadas.</li><li>Confira as informações e toque em <strong>Salvar</strong>.</li></ol>
<figure><div class="match-demo"><span>Jogador A</span><strong>2 × 1</strong><span>Jogador B</span></div><figcaption>Exemplo fictício. Zero a zero é um resultado válido: preencha os dois campos com 0.</figcaption></figure>
<p>A classificação é recalculada após o salvamento. Para remover um resultado, apague os <strong>dois</strong> gols e salve. Essa ação também remove a data registrada para o resultado.</p><div class="tip">O painel permite corrigir um jogo depois da data da partida, respeitando os jogos que sua conta pode acessar. As alterações ficam na auditoria.</div></section>
<aside class="intro"><h2>Avisos de resultado por e-mail</h2><p>Quando um placar ou a data do jogo for registrado, corrigido ou removido, os dois botonistas receberão um aviso se tiverem um e-mail válido na conta vinculada. Isso vale para o painel e para o QR da súmula. O aviso traz o confronto, o placar, a data e o link do site; em correções, mostra também os dados anteriores.</p><p>Salvar sem mudar nada não envia outro aviso. Os avisos são enviados após salvar. Se o e-mail falhar, o resultado permanece salvo. O administrador máximo pode tentar reenviar na Auditoria; avisos já confirmados não são repetidos. A atualização não envia avisos retroativos. As cópias ao organizador dependem do endereço definido pelo responsável na configuração privada do sistema.</p></aside><section id="sumula"><p class="step">04 · NA MESA DE JOGO</p><h2>Imprima a súmula com antecedência</h2><p>A súmula é a ficha da partida, com espaço para placar, local, horário, árbitro, observações e assinaturas.</p>
<figure><svg viewBox="0 0 660 170" role="img" aria-labelledby="flow-title flow-desc"><title id="flow-title">Da geração da súmula ao registro do placar</title><desc id="flow-desc">Primeiro escolha a data, depois imprima a súmula. No dia escolhido, use o QR Code para enviar o resultado.</desc><g fill="#edf4e5" stroke="#123e32" stroke-width="2"><rect x="8" y="15" width="190" height="140" rx="15"/><rect x="235" y="15" width="190" height="140" rx="15"/><rect x="462" y="15" width="190" height="140" rx="15"/></g><g fill="#123e32" font-family="Arial,sans-serif" text-anchor="middle"><text x="103" y="58" font-size="30">1</text><text x="103" y="97" font-size="20">Escolha a data</text><text x="330" y="58" font-size="30">2</text><text x="330" y="97" font-size="20">Imprima</text><text x="557" y="58" font-size="30">3</text><text x="557" y="97" font-size="20">Envie o placar</text><text x="557" y="129" font-size="16">no dia do jogo</text><text x="216" y="91" font-size="24">→</text><text x="443" y="91" font-size="24">→</text></g></svg><ol class="flow-mobile"><li><strong>Escolha a data</strong><br>Informe o dia da partida.</li><li><strong>Imprima</strong><br>Confira os nomes e a data.</li><li><strong>Envie o placar</strong><br>Use o QR no dia do jogo.</li></ol><figcaption>Você pode imprimir hoje e usar a súmula em uma data futura.</figcaption></figure>
<ol><li>Em um jogo sem resultado, toque em <strong>Gerar súmula com QR</strong> e entre com uma conta autorizada, se solicitado. No painel, use o botão QR.</li><li>Escolha a <strong>data do jogo</strong>: hoje ou uma data futura, em qualquer dia da semana.</li><li>Confira os nomes e a data. Use <strong>Alterar data</strong> se necessário e depois <strong>Imprimir súmula</strong>.</li><li>No dia indicado, o árbitro pode ler o QR com a câmera do celular, informar os dois placares e confirmar.</li></ol>
<div class="tip"><strong>O QR funciona somente na data impressa e aceita um único envio.</strong> Essa data é gravada junto ao placar. Gerar ou imprimir a ficha não registra um resultado. Jogo com resultado salvo não permite gerar outra súmula.</div><p>Se houver erro após o envio, procure quem tem acesso ao jogo no painel. Guarde o QR com cuidado: quem tiver o código poderá enviar o resultado dentro da validade. O sistema identifica quem gerou a súmula, mas não confirma a identidade de quem está usando o celular.</p></section>
<section id="nomes"><p class="step">05 · SEU CADASTRO</p><h2>Corrija a grafia do seu nome</h2><p>Entre no painel, abra <strong>Meu nome</strong>, ajuste a grafia e toque em <strong>Salvar nome</strong>. Você só pode corrigir o botonista vinculado à sua conta. Administradores usam <strong>Botonistas</strong> para corrigir os cadastros.</p><figure><div class="name-demo"><span>Luca Montteiro</span><b aria-label="corrigido para">→</b><strong>Luca Monteiro</strong></div><figcaption>Exemplo com nome fictício, apenas para ilustrar a correção de grafia. Os jogos, pontos e resultados continuam vinculados ao mesmo participante.</figcaption></figure><p>A correção não muda seu login, senha ou nome da conta de acesso. Documentos já impressos continuam com a grafia anterior. Nomes vazios ou iguais aos de outro botonista não são aceitos.</p></section>
<section id="perfis"><p class="step">06 · CADA UM COM SEU ACESSO</p><h2>Entenda as permissões</h2><div class="roles"><article><h3>Botonista</h3><p>Consulta a área pública, salva resultados dos próprios jogos, gera suas súmulas e corrige o próprio nome.</p></article><article><h3>Administrador</h3><p>Gerencia todos os jogos, corrige nomes, consulta a auditoria e pode criar e baixar backups.</p></article><article><h3>Administrador máximo</h3><p>Tem os acessos administrativos e também gerencia usuários, altera privilégios e restaura backups. É o acesso principal da organização.</p></article></div><p>O administrador máximo usa <strong>Usuários → Alterar privilégios</strong>. Para o nível Botonista, deve selecionar o jogador vinculado. A nova permissão vale na próxima ação do usuário, mesmo que ele já esteja conectado. Ao desativar uma conta, os convites pendentes também são cancelados. Links antigos não permitem reativar o acesso; para autorizá-lo novamente por convite, o administrador máximo precisa emitir um novo link.</p></section>
<section id="auditoria"><p class="step">07 · HISTÓRICO E CÓPIAS DE SEGURANÇA</p><h2>Consulte o que mudou</h2><p>Na <strong>Auditoria</strong>, administradores filtram por período, responsável e ação. Abra <strong>Ver detalhes da alteração</strong> para comparar os valores anteriores e novos. São registrados resultados, súmulas, nomes, usuários, privilégios, convites e operações de backup. Senhas e códigos de acesso não são exibidos.</p><p>O administrador máximo também pode consultar tentativas de entrada, bloqueios e autenticações aceitas, com login informado e origem da conexão. Senhas nunca são registradas. O histórico começa após a instalação da auditoria; ações anteriores não são reconstruídas. Não há opção de editar ou apagar os registros pelo painel.</p><h3>Avisos por e-mail</h3><p>A organização recebe avisos quando um botonista salva ou remove um resultado, corrige o nome, gera uma súmula ou ativa sua conta por convite. Resultados enviados por QR também geram aviso. Senhas e tokens não são enviados.</p><p>Na auditoria, o estado do aviso mostra se o servidor de e-mail o aceitou ou se houve falha. Uma falha no envio não desfaz o salvamento. O acesso principal pode usar Tentar enviar aviso novamente para avisos pendentes ou com falha. Não é necessário configurar agendamento. A aceitação pelo servidor não confirma a chegada à caixa de entrada; verifique também o spam.</p><h3>Como usar os backups</h3><p>Em <strong>Backup</strong>, use <strong>Criar backup agora</strong> para guardar uma cópia do banco e <strong>Baixar</strong> para salvar uma cópia em local protegido.</p><div class="tip"><strong>Restaurar é diferente de baixar.</strong> A restauração substitui os dados atuais pelos da cópia escolhida, podendo recuperar resultados e permissões antigas. Somente o administrador máximo pode fazê-la. O sistema guarda uma cópia do estado anterior e preserva o histórico de auditoria.</div></section>
<section id="duvidas"><p class="step">08 · RESPOSTAS RÁPIDAS</p><h2>Precisa de ajuda?</h2><details><summary>O QR não funciona hoje. Por quê?</summary><p>Confira a data da súmula. Ele só aceita o envio nesse dia. Também pode já ter sido usado ou o jogo pode ter recebido resultado pelo painel.</p></details><details><summary>Não vejo todos os jogos no painel.</summary><p>Uma conta de botonista mostra apenas seus jogos. Confira também os filtros. Se o vínculo estiver errado, procure o administrador máximo.</p></details><details><summary>Esqueci minha senha.</summary><p>Peça ao administrador máximo para reenviar o convite e use o novo link para definir uma senha.</p></details><details><summary>Como sei qual versão estou usando?</summary><p>A versão aparece no rodapé da área pública e do painel. Clique nela para abrir os créditos, conhecer o desenvolvedor e consultar seu contato. Para fechar, use o botão Fechar, a tecla Esc ou toque fora da janela. Esta entrega é a <?= copaVersion() ?>. Cada nova implementação aumenta 0,01: a próxima será <?= number_format((COPA_VERSION_NUMBER + 1) / 100, 2, '.', '') ?>.</p></details><details><summary>O site parece não ter atualizado.</summary><p>Recarregue a página. No computador, tente Ctrl + F5. Se continuar diferente, informe ao responsável a versão exibida e a tela em que percebeu o problema.</p></details></section>
<?= copaHelpFooter() ?></main></body></html>
