<?php
require __DIR__ . '/referee.php';
$pdo->exec("INSERT INTO users(id,name,username,email,player_id,is_active,created_at) VALUES (1,'A','a','a@example.invalid',1,1,'2026-09-27'),(2,'B','b','b@example.invalid',2,1,'2026-09-27')");
$_SESSION = ['legacy_admin'=>true];
$insertGame->execute([301,301]);
$GLOBALS['testEmails']=[];
savePanelResult(301,2,1,date('Y-m-d'));
check(count($GLOBALS['testEmails'])===3,'administrator result notifies both linked players');
check(str_contains($GLOBALS['testEmails'][0]['text'],'2 x 1') && str_contains($GLOBALS['testEmails'][0]['text'],'index.php#jogos'),'score and public link');
savePanelResult(301,2,1,date('Y-m-d'));
check(count($GLOBALS['testEmails'])===3,'unchanged result sends nothing');
savePanelResult(301,3,1,date('Y-m-d'));
check(count($GLOBALS['testEmails'])===6 && str_contains($GLOBALS['testEmails'][3]['text'],'Antes: 2 x 1'),'correction includes previous score');
$pdo->exec("UPDATE users SET email='invalid' WHERE id=2");
savePanelResult(301,4,1,date('Y-m-d'));
check(count($GLOBALS['testEmails'])===8,'invalid email skipped');
$pdo->exec("UPDATE users SET email='' WHERE id=2");
savePanelResult(301,5,1,date('Y-m-d'));
check(count($GLOBALS['testEmails'])===10,'empty email skipped');
$GLOBALS['testSmtpFailure']=true;
savePanelResult(301,6,1,date('Y-m-d'));
check(gameById(301)['score_a']===6,'SMTP failure preserves score');
$GLOBALS['testSmtpFailure']=false;
$failed=$pdo->query("SELECT event_id FROM email_notifications WHERE status='failed' ORDER BY rowid DESC LIMIT 1")->fetchColumn();
$pdo->prepare("UPDATE email_notifications SET status='pending' WHERE event_id=? AND status='failed'")->execute([$failed]);
sendPlayerNotification($failed);sendPlayerNotification($failed);
check(count($GLOBALS['testEmails'])===12,'retry sends only once');
savePanelResult(301,null,null,'');
check(str_contains($GLOBALS['testEmails'][count($GLOBALS['testEmails'])-2]['text'],'Sem resultado'),'removal notifies players');
$link=dailyRefereeLink(301); $_SESSION=[];
$prior=count($GLOBALS['testEmails']); saveRefereeResult($link['token'],1,0);
check(count($GLOBALS['testEmails'])===$prior+2,'QR notifies player and organizer');

$_SESSION=['legacy_admin'=>true];
$pdo->exec("UPDATE users SET email='b@example.invalid' WHERE id=2");
$GLOBALS['testFailRecipient']='b@example.invalid';
$prior=count($GLOBALS['testEmails']);
savePanelResult(301,7,0,date('Y-m-d'));
check(count($GLOBALS['testEmails'])===$prior+2,'one recipient failure does not block the other');
$failed=$pdo->query("SELECT event_id FROM email_notifications WHERE status='failed' ORDER BY rowid DESC LIMIT 1")->fetchColumn();
$GLOBALS['testFailRecipient']='';
$pdo->prepare("UPDATE email_notifications SET status='pending' WHERE event_id=? AND status='failed'")->execute([$failed]);
sendPlayerNotification($failed);
check(count($GLOBALS['testEmails'])===$prior+3 && end($GLOBALS['testEmails'])['recipient']==='b@example.invalid','retry excludes successful recipient');
// Recreate the old schema with one previously sent notice, then migrate twice.
$pdo->exec('DROP TABLE email_notifications');
$pdo->exec("CREATE TABLE email_notifications(event_id TEXT PRIMARY KEY REFERENCES audit_log(event_id), recipient TEXT NOT NULL,status TEXT NOT NULL DEFAULT 'pending',attempts INTEGER NOT NULL DEFAULT 0, attempted_at TEXT NULL,sent_at TEXT NULL)");
$pdo->prepare("INSERT INTO email_notifications VALUES (?,'legacy@example.invalid','sent',2,'2026-09-27','2026-09-27')")->execute([$failed]);
initialiseNotifications();initialiseNotifications();
$row=$pdo->query('SELECT * FROM email_notifications')->fetch();
check($row['status']==='sent' && $row['attempts']===2 && $row['recipient']==='legacy@example.invalid' && $row['audience']==='organizer','migration preserves old delivery state and is idempotent');
